name: Lint Code Base


on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu_latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Super Linter
        uses: super-linter/super-linter@v5.4.0
